[tool.poetry]
name = "divination"
version = "0.1.0"
description = ""
authors = ["SlashNephy <spica@starry.blue>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
