name: Build (Common)

on:
  push:
    paths:
      - 'Common/**'
    branches:
      - 'master'

  pull_request:
    paths:
      - 'Common/**'
    types:
      - opened
      - synchronize

  release:
    types:
      - created

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          # GitVersion
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Download Dalamud
        run: |
          Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/${env:DALAMUD_BRANCH}/latest.zip -OutFile latest.zip
          Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev\"
        env:
          DALAMUD_BRANCH: stg

      - name: Build
        run: dotnet build --configuration Release
        working-directory: Common

      - name: Publish
        if: github.event_name != 'pull_request'
        run: |
          dotnet pack --configuration Release --include-source
          dotnet nuget push bin\Release\*.symbols.nupkg `
            --source https://api.nuget.org/v3/index.json `
            --api-key ${{ secrets.NUGET_API_KEY }} `
            --skip-duplicate
        working-directory: Common
