name: Build (Server.Companion)

on:
  push:
    paths:
      - 'packages/Server.Companion/**'
  release:
    types:
      - published
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  actions: read
  security-events: write

jobs:
  build:
    uses: SlashNephy/.github/.github/workflows/docker-build.yml@master
    with:
      image-name: ghcr.io/slashnephy/divination-server-companion
      image-platforms: linux/amd64
      context: packages/Server.Companion
