name: Check (DiscordBot)

on:
  pull_request:
    paths:
      - 'packages/DiscordBot/**'
    types:
      - opened
      - synchronize
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check:
    uses: SlashNephy/.github/.github/workflows/gradle-run.yml@master
    with:
      task: build
      working-directory: packages/DiscordBot
