name: 'CI (AetheryteLinkInChat)'

on:
  push:
    paths:
      - 'packages/plugins/AetheryteLinkInChat'
  pull_request:
    paths:
      - 'packages/plugins/AetheryteLinkInChat'
    types:
      - opened
      - synchronize
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  build:
    uses: SlashNephy/Divination/.github/workflows/reusable-build-plugin.yml@master
    with:
      plugin-name: 'Divination.AetheryteLinkInChat'
      working-directory: 'packages/plugins/AetheryteLinkInChat'
    permissions:
      contents: read
      actions: write

  deploy:
    if: github.event_name != 'pull_request' && github.ref == 'refs/heads/master'
    needs: build
    uses: SlashNephy/Divination/.github/workflows/reusable-deploy-plugin.yml@master
    with:
      plugin-name: 'Divination.AetheryteLinkInChat'
    secrets:
      DEPLOY_GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
    permissions:
      contents: write
      actions: read

  format:
    if: github.event_name == 'push'
    uses: SlashNephy/.github/.github/workflows/dotnet-format.yml@master
    permissions:
      contents: write
